<?php

namespace WPSpeedo_Team;

if ( ! defined('ABSPATH') ) exit;

return [
    'desktop' => _x('Desktop', 'Editor', 'wpspeedo-team'),
    'tablet' => _x('Tablet', 'Editor', 'wpspeedo-team'),
    'small-tablet' => _x('Small Tablet', 'Editor', 'wpspeedo-team'),
    'mobile' => _x('Mobile', 'Editor', 'wpspeedo-team'),

    'something-wrong' => _x('Something went wrong!', 'Editor', 'wpspeedo-team'),

    'this-is-pro' => _x('Pro feature', 'Editor', 'wpspeedo-team'),
    'purchasing-premium' => _x('If you love our work please support us by purchasing our Premium plugin.', 'Editor', 'wpspeedo-team'),
    'upgrade-to-pro' => _x('Upgrade to Pro', 'Editor', 'wpspeedo-team'),
    'documentation' => _x('Documentation', 'Editor', 'wpspeedo-team'),
    'save-settings' => _x('Save Settings', 'Editor', 'wpspeedo-team'),
    'back' => _x('Back', 'Editor', 'wpspeedo-team'),
    'save' => _x('Save', 'Editor', 'wpspeedo-team'),
    'shortcode-copied' => _x('Shortcode Copied', 'Editor', 'wpspeedo-team'),
    'copy-shortcode' => _x('Copy Shortcode', 'Editor', 'wpspeedo-team'),
    'php-code-copied' => _x('PHP Code Copied', 'Editor', 'wpspeedo-team'),
    'copy-php-code' => _x('Copy PHP Code', 'Editor', 'wpspeedo-team'),
    'search-settings' => _x('Search Settings', 'Editor', 'wpspeedo-team'),
    'shortcodes' => _x('Shortcodes', 'Editor', 'wpspeedo-team'),
    'search-shortcode' => _x('Search Shortcode', 'Editor', 'wpspeedo-team'),
    'type' => _x('Type', 'Editor', 'wpspeedo-team'),
    'name' => _x('Name', 'Editor', 'wpspeedo-team'),
    'shortcode' => _x('Shortcode', 'Editor', 'wpspeedo-team'),
    'php-code' => _x('PHP Code', 'Editor', 'wpspeedo-team'),
    'copied' => _x('Copied', 'Editor', 'wpspeedo-team'),
    'copy' => _x('Copy', 'Editor', 'wpspeedo-team'),
    'rename' => _x('Rename', 'Editor', 'wpspeedo-team'),
    'edit' => _x('Edit', 'Editor', 'wpspeedo-team'),
    'clone' => _x('Clone', 'Editor', 'wpspeedo-team'),
    'no-shortcode-found' => _x('No shortcode found.', 'Editor', 'wpspeedo-team'),
    'create-new-shortcode' => _x('Create New Shortcode', 'Editor', 'wpspeedo-team'),
    'shortcode-name' => _x('Shortcode Name', 'Editor', 'wpspeedo-team'),
    'create-shortcode' => _x('Create Shortcode', 'Editor', 'wpspeedo-team'),
    'rename-shortcode' => _x('Rename Shortcode', 'Editor', 'wpspeedo-team'),
    'add-shortcode-name' => _x('Please add a shortcode name', 'Editor', 'wpspeedo-team'),
    'are-you-sure' => _x('Are you sure?', 'Editor', 'wpspeedo-team'),
    'want-to-delete-shortcode' => _x('Do you want to delete (%s) shortcode?', 'Editor', 'wpspeedo-team'),
    'cancel' => _x('Cancel', 'Editor', 'wpspeedo-team'),
    'delete' => _x('Delete', 'Editor', 'wpspeedo-team'),
    'got-questions' => _x('Got questions?', 'Editor', 'wpspeedo-team'),
    'got-questions-desc' => _x('Please submit a ticket if you face any issue or if you have any question.', 'Editor', 'wpspeedo-team'),
    'submit-ticket' => _x('Submit Your Ticket', 'Editor', 'wpspeedo-team'),
    'shortcodes' => _x('Shortcodes', 'Editor', 'wpspeedo-team'),
    'settings' => _x('Settings', 'Editor', 'wpspeedo-team'),
    'order' => _x('Order', 'Editor', 'wpspeedo-team'),
    'go-premium' => _x('Go Premium', 'Editor', 'wpspeedo-team'),
    'demo-import' => _x('Demo Import', 'Editor', 'wpspeedo-team'),
    'purge-cache' => _x('Purge Cache', 'Editor', 'wpspeedo-team'),
    'bulk-import' => _x('Bulk Import', 'Editor', 'wpspeedo-team'),
    'export-import' => _x('Export/Import', 'Editor', 'wpspeedo-team'),
    'tools' => _x('Tools', 'Editor', 'wpspeedo-team'),
    'members' => Utils::get_setting( 'member_plural_name' ),
    'group' => Utils::get_setting( 'group_plural_name' ),
    'location' => Utils::get_setting( 'location_plural_name' ),
    'language' => Utils::get_setting( 'language_plural_name' ),
    'specialty' => Utils::get_setting( 'specialty_plural_name' ),
    'gender' => Utils::get_setting( 'gender_plural_name' ),
    'extra_one' => Utils::get_setting( 'extra_one_plural_name' ),
    'extra_two' => Utils::get_setting( 'extra_two_plural_name' ),
    'extra_three' => Utils::get_setting( 'extra_three_plural_name' ),
    'extra_four' => Utils::get_setting( 'extra_four_plural_name' ),
    'extra_five' => Utils::get_setting( 'extra_five_plural_name' ),
];